apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: test
spec:
  # Optional: Set the storage class or omit to accept the default
  source:
    http:
      url: "https://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: rook-ceph-block 
