apiVersion: kubevirt.io/v1alpha3
#kind: VirtualMachineInstance
kind: VirtualMachine
metadata:
  name: fedora-vm
spec:
  running: true
  #terminationGracePeriodSeconds: 30
  template:
    spec:
      domain:
        resources:
          requests:
            memory: 1024M
        devices:
          disks:
          - name: containerdisk
            disk:
              bus: virtio
          - name: disk-1
            disk:
              bus: virtio
          - disk:
              bus: virtio
            name: cloudinitdisk
      volumes:
      - name: containerdisk
        containerDisk:
          image: kubevirt/fedora-cloud-container-disk-demo:latest
      - name: disk-1
        persistentVolumeClaim:
          claimName: fedora-1
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |-
            #cloud-config
            password: fedora
            chpasswd: { expire: False }

